### PR TITLE
Refactor: simplify file request handling

### PR DESCRIPTION
**Pull request by flosse**

### CODE REVIEW

**Comment by flosse** [comment]
...it's not ready to merge yet because I made a small mistake :see_no_evil:

**Comment by flosse** [comment]
... after several approaches I'd switch back to your initial implementation :neutral_face:
If you like, I can modify this PR to do so in addition to the tests + usual file naming (`.gz` and `.br`).

**Comment by MartinKavik** [comment]
> If you like, I can modify this PR to do so in addition to the tests + usual file naming (.gz and .br).

It would be nice :) Thanks!

**Comment by flosse** [comment]
done :)

**Comment by flosse** [comment]
...and some more small refactoring ;-)

**Pull request merged**
