### PR TITLE
add method `Link::new_tab_with_target`

### PR DESCRIPTION
**Pull request by databasedav**

### CODE REVIEW

**Comment by MartinKavik** [comment]
1. What's your motivation / use-case?
2. What `target` values do you plan to use and when?
Thanks!

**Comment by databasedav** [comment]
specifying the target prevents a new tab from opening every time a link is clicked if given a target that already exists, a good example is spam opening multiple checkout sessions, specifying a single `"checkout_session"` target means only one checkout session tab can be open in the browser at a time

**Comment by MartinKavik** [comment]
> specifying the target prevents a new tab from opening every time a link is clicked if given a target that already exists

Then maybe a method like `Link::new_tab_once()` would be better to cover just the described use-case. It would set the `target` value to a value derived (e.g. hashed) from the link url or to a random/unique value (just first ideas).

> a good example is spam opening multiple checkout sessions

Honestly, I have never seen a custom `target` value (aka _framename_) in tutorials or in code in practice. Also custom `target` values have been deprecated for a while and then allowed to use again if I'm not mistaken. So I had to do some research before writing this comment.

I haven't heard about problems like "spam opening multiple tabs" - could you point me to some related articles or other materials? I don't know how it should work.

Also what about `rel="noopener"` - is it set when you define a custom `target`? It should be set automatically by browsers with `_blank` values but I'm not sure how it works with custom values. Related docs:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener
- https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

The name `new_tab_with_target` would also lie in many cases - e.g. `new_tab_with_target("_self")` wouldn't open a new tab at all. Also I don't like HTML naming like `_self` or `_blank` and untyped string values, we would need to design a better API if we decide to support  all `target` values. First ideas are names like `frame_name` or `browsing_context`.
Finally, if we decide to support multiple `target` values then we should think about their relations to _frames_ because it's a quite complex topic, see e.g. https://html.spec.whatwg.org/multipage/browsers.html#browsing-context-names.

And what about users? I would - as a website user - probably expect that the external link (e.g. tagged with an arrow icon) will always open in a new tab. Is there any related UX best practices?

**Comment by databasedav** [comment]
@MartinKavik i agree with all of this, my "spam opening multiple tabs" problem doesn't actually happen in the context of a visible link so the example isn't perfect but it would go something like this: there's a link that opens a unique checkout session (managed externally, e.g. by [stripe](https://stripe.com/docs/payments/checkout)) on each click, we don't actually care that the link is being spammed open (although we care a tiny bit because we don't want to spam stripe), we just want to minimize the number of checkout sessions that a naive actor can have open within the same browser

would renaming the function to simply `target` be ok for exposing the low level api?

**Comment by MartinKavik** [comment]
The code has been changed since the PR has been created and also we would probably need to implement compile-time checks to ensure you can't call both `new_tab` and `target` methods at once.

I'm closing it, but if the problem is still relevant, please write on Discord or create a new issue with updated context for your use-cases, please. Thanks!

**Pull request closed without merging**
